services:
  - name: app
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn spearhead_api.wsgi --bind 0.0.0.0:$PORT
    envVars:
      DJANGO_SETTINGS_MODULE: "spearhead_api.settings"
    healthCheckPath: "/admin/"
