services:
  - name: db
    plan: starter
    env:
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: ${DB_PORT}
    addons:
      - type: postgres

  - name: app
    plan: starter
    buildCommand: |
      docker build -t spearhead_app .
    startCommand: |
      docker run -e PORT=$PORT -e DB_NAME=$DB_NAME -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -p $PORT:$PORT spearhead_app
    env:
      - key: PORT
        fromType: user-supplied
    source_mount:
      path: .
      mount_path: /code
